/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bugreportapplication;
import bugreportapplication.model.BugReport;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author David
 */
public class bugReportInitial extends javax.swing.JFrame {

    /**
     * Creates new form bugReportInitial
     */
    
    private final ArrayList<BugReport> unresolvedBugReports;
    private final ArrayList<BugReport> resolvedBugReports;
    private final DefaultListModel<String> resolvedModel;
    private final DefaultListModel<String> unresolvedModel;
    
    public bugReportInitial() {
        initComponents();
        // manually add all bugs in the database
        ArrayList<BugReport> bugs = AccessDB.getReports();
        unresolvedBugReports = new ArrayList<BugReport>();
        resolvedBugReports = new ArrayList<BugReport>();
        resolvedModel = new DefaultListModel<>();
        unresolvedModel = new DefaultListModel<>();
                
        for (BugReport bug : bugs) {
            if (bug.getStatus().equals("Unresolved")) {
                unresolvedBugReports.add(bug);
                unresolvedModel.addElement(bug.getTitle());
            } else {
                resolvedBugReports.add(bug);
                resolvedModel.addElement(bug.getTitle());
            }
        }
        
        this.unresolvedBugs.setModel(unresolvedModel);
        this.resolvedBugs.setModel(resolvedModel);
        
        
        MouseListener mouseListenerResolved = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int pos = resolvedBugs.locationToIndex(e.getPoint());
                resolvedBugs.setSelectedIndex(pos);
            }
        };
    
        MouseListener mouseListenerUnresolved = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int pos = unresolvedBugs.locationToIndex(e.getPoint());
                unresolvedBugs.setSelectedIndex(pos);
            }
        };
    
    
    resolvedBugs.addMouseListener(mouseListenerResolved);
    unresolvedBugs.addMouseListener(mouseListenerUnresolved);
        
                
        // Set frame to be visible
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        unresolvedBugs = new javax.swing.JList<>();
        userMsg = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resolvedBugs = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sprintGraphBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 475));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bug Report System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("List of Bugs");

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        unresolvedBugs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unresolvedBugs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unresolvedBugsMouseClicked(evt);
            }
        });
        unresolvedBugs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                unresolvedBugsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(unresolvedBugs);

        userMsg.setForeground(new java.awt.Color(0, 204, 51));

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        resolvedBugs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resolvedBugs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resolvedBugsMouseClicked(evt);
            }
        });
        resolvedBugs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resolvedBugsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(resolvedBugs);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Resolved Bugs");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Unresolved Bugs");

        sprintGraphBtn.setText("Sprint Graph");
        sprintGraphBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprintGraphBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(userMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sprintGraphBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(userMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprintGraphBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // when viewBtn is clicked -> open up details about the bug itself
        // if not selected then inform user to select button, otherwise you can do it 
        if (unresolvedBugs.getSelectedIndex() == -1 && resolvedBugs.getSelectedIndex() == -1) {
            userMsg.setForeground(Color.red);
            userMsg.setText("Select a bug before clicking the button");
        // if unresolved bug
        } else if (!(unresolvedBugs.getSelectedIndex() == -1)) {
            dispose();
            bugReportView frame = new bugReportView(unresolvedBugReports.get(unresolvedBugs.getSelectedIndex()));
            frame.setVisible(true);
        } else {
            dispose();
            bugReportView frame = new bugReportView(resolvedBugReports.get(resolvedBugs.getSelectedIndex()));
            frame.setVisible(true);
        }
        
    }//GEN-LAST:event_viewBtnActionPerformed

    private void removeBugDB(BugReport bug) {
        AccessDB.deleteReport(bug.getTitle(), bug.getDesc(), bug.getPriority());
    }
    
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // Remove a bug first in local arrayList
        if (unresolvedBugs.getSelectedIndex() == -1 && resolvedBugs.getSelectedIndex() == -1) {
            userMsg.setForeground(Color.red);
            userMsg.setText("Select a bug before clicking the button");
        } else if (!(unresolvedBugs.getSelectedIndex() == -1)) {
            // Remove element from list and update
            BugReport removed = unresolvedBugReports.remove(unresolvedBugs.getSelectedIndex());
            removeBugDB(removed);
            unresolvedModel.removeElement(removed.getTitle());
            this.unresolvedBugs.setModel(unresolvedModel);
            userMsg.setForeground(new Color(0,204,51));
            userMsg.setText(removed.getTitle() + " has been successfully removed.");
        } else {
            // Remove element from list and update
            BugReport removed = resolvedBugReports.remove(resolvedBugs.getSelectedIndex());
            removeBugDB(removed);
            resolvedModel.removeElement(removed.getTitle());
            this.resolvedBugs.setModel(resolvedModel);
            userMsg.setForeground(new Color(0,204,51));
            userMsg.setText(removed.getTitle() + " has been successfully removed.");
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        dispose();
        ArrayList<BugReport> temp = new ArrayList<BugReport>();
        temp.addAll(resolvedBugReports);
        temp.addAll(unresolvedBugReports);
        bugReportForm frame = new bugReportForm(temp);
        frame.setVisible(true);
    }//GEN-LAST:event_createBtnActionPerformed

    private void unresolvedBugsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unresolvedBugsMouseClicked
        viewBtn.setVisible(true);
    }//GEN-LAST:event_unresolvedBugsMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        dispose();
        Logout screen = new Logout();
        screen.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    
    
    private void unresolvedBugsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_unresolvedBugsValueChanged
        // Error message gone now selected and other jlist is deselected
            userMsg.setText("");
            resolvedBugs.clearSelection();
            
    }//GEN-LAST:event_unresolvedBugsValueChanged

    private void resolvedBugsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolvedBugsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resolvedBugsMouseClicked

    
    private void resolvedBugsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resolvedBugsValueChanged
        // Error message gone now selected and other jlist is deselected        
        userMsg.setText("");
        unresolvedBugs.clearSelection();
    }//GEN-LAST:event_resolvedBugsValueChanged

    private void sprintGraphBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprintGraphBtnActionPerformed
        bugReportGraph screen = new bugReportGraph();
        screen.setVisible(true);
    }//GEN-LAST:event_sprintGraphBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bugReportInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bugReportInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bugReportInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bugReportInitial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {    
                new bugReportInitial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JList<String> resolvedBugs;
    private javax.swing.JButton sprintGraphBtn;
    private javax.swing.JList<String> unresolvedBugs;
    private javax.swing.JLabel userMsg;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
