package bugreportapplication;
import bugreportapplication.model.BugReport;

/**
 *
 * @author David Liu, Longric Tran, Refath Ahmed, Tao Wang, Vito Carnovale (Group #33)
 *
 * Represents a bugReportView class for displaying a more detailed look into a bug report
 */
public class bugReportView extends javax.swing.JFrame {

    /**
     * Creates new form bugReportView
     * @param bug
     */
    
    private final BugReport bug;
    
    public bugReportView(BugReport bug) {
        initComponents();
        
        this.bug = bug;
        
        // If the status of the bug is already resolved, disable resolved button
        if (bug.getStatus().equals("Resolved")) {
            resolveBugBtn.setEnabled(false);
            editBtn.setEnabled(false);
        }
        
        // ensure that desc isn't writeable
        bugDesc.setFocusable(false);
        
        // fill in information for bug
        bugName.setText("Title: " + bug.getTitle());
        bugDesc.setText(bug.getDesc());
        bugPriority.setText("Priority: " + bug.getPriority());
        bugStatus.setText("Status: " + bug.getStatus());
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bugName = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        bugDesc = new javax.swing.JTextArea();
        bugPriority = new javax.swing.JLabel();
        bugStatus = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        resolveBugBtn = new javax.swing.JButton();
        resolvedMsg = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bugName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bugName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bugName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bugDesc.setColumns(20);
        bugDesc.setRows(5);
        scrollPanel.setViewportView(bugDesc);

        bugPriority.setBackground(new java.awt.Color(153, 153, 153));
        bugPriority.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bugPriority.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bugPriority.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bugStatus.setBackground(new java.awt.Color(153, 153, 153));
        bugStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bugStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bugStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        returnBtn.setBackground(new java.awt.Color(204, 204, 204));
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        resolveBugBtn.setBackground(new java.awt.Color(204, 204, 204));
        resolveBugBtn.setText("Resolve");
        resolveBugBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolveBugBtnActionPerformed(evt);
            }
        });

        resolvedMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resolvedMsg.setForeground(new java.awt.Color(51, 204, 0));

        editBtn.setBackground(new java.awt.Color(204, 204, 204));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resolvedMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resolveBugBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(bugName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bugPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bugStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bugName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bugPriority, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bugStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(resolvedMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resolveBugBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        dispose();
        bugReportInitial frame = new bugReportInitial();
        frame.setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void resolveBugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolveBugBtnActionPerformed
        AccessDB.resolveReport(bug.getTitle(), bug.getDesc(), bug.getPriority());
        
        // Now moved to resolve so disable the button
        resolveBugBtn.setEnabled(false);
        bugStatus.setText("Status: Resolved");
        resolvedMsg.setText("Bug has successfully been resolved");
        
    }//GEN-LAST:event_resolveBugBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        dispose();
        bugReportForm screen = new bugReportForm(bug);
        screen.setVisible(true);
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bugReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bugReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bugReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bugReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bugReportView(new BugReport()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bugDesc;
    private javax.swing.JLabel bugName;
    private javax.swing.JLabel bugPriority;
    private javax.swing.JLabel bugStatus;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resolveBugBtn;
    private javax.swing.JLabel resolvedMsg;
    private javax.swing.JButton returnBtn;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
